name: First Workflow
 
on:
  workflow_dispatch:
 
jobs:
  first_job:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Say hello
        run: echo "Hello from the first job!"
